import { readFileSync } from "node:fs";
import { parseDxf, polygonsOfLayer, linesOfLayer } from "@/lib/dxf";
import { defaultParams, optimizeBlock } from "@/lib/parcelation";
import { ringArea } from "@/lib/geo";
const d = parseDxf(readFileSync("/mnt/user-uploads/340_ADA_KAMU_ALANLI.DXF","latin1"));
const ada = polygonsOfLayer(d,"ADA_ALAN")[0];
const kamu = polygonsOfLayer(d,"KAMU_ALANI");
const t = Date.now();
const b = optimizeBlock(ada, [], {...defaultParams}, { id:"a", name:"340", variant:0, publicRings: kamu });
console.log("sure(s)", ((Date.now()-t)/1000).toFixed(1), "adaAlan", ringArea(ada).toFixed(1), "parsel", b.parcels.length, "gecerli", b.parcels.filter(x=>x.valid).length, "artik", b.leftoverArea.toFixed(1));
for (const q of b.parcels) console.log(q.no, q.area.toFixed(1), "cephe", q.frontage.toFixed(1), "derinlik", q.depth.toFixed(1), q.valid?"OK":"X "+q.issues.join("|"));
